//
//  Constant.m
//  StackOverflowClient
//
//  Created by Sam Wong on 12/11/2014.
//  Copyright (c) 2014 Sam Wong. All rights reserved.
//

#import "Constant.h"


NSString * const koAuthToken = @"oAuthToken";
NSString * const kLoginURL = @"https://stackexchange.com/oauth/dialog?client_id=3855&scope=no_expiry&redirect_uri=https://stackexchange.com/oauth/login_success";

// these client strings are generated by StackExchangeAPI -> Apps
// these info can be found on http://stackapps.com/apps/oauth/view/3855

NSString * const kClientId = @"3855";
NSString * const kPublicKey = @"n)5yDcr5enm7pgAvCAAcHQ((";
NSString * const koAuthDomain = @"https://stackexchange.com/oauth/login_success";
NSString * const koAuthURL = @"https://stackexchange.com/oauth/dialog";

//NSString * const kClientSecret = @"Pw3RLlRJEqx4uX97dC2Fzw((";

